title: Kristin Lüpken # your name (or website title) here
logo: "images/CV Pic 3-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Business Intelligence | Marketing Strategy | Data Analytics | Product Management
  <br><br>
  My competency lies in understanding and driving businesses from a marketing perspective. I'm good at bringing direction, structure and clarity to complex matters. I like to work in teams and organisations that value cooperation, humour and authenticity and give me the flexibility to excel at my job.
  <br><br>
  <a href="https://www.linkedin.com/in/kristin-l%C3%BCpken-b4149984/">LinkedIn Profile</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/kristin.l.pken/vizzes">Public Tableau</a> 
  <br>
  <a href="https://github.com/klue-git">GitHub Repo</a> 
  <br>
  <a href="pdf/Data Analytics Portfolio Kristin Lüpken.pdf">Data Analytics Project Portfolio PDF</a> 
  <br>
  <a href="pdf/Product Management Portfolio Kristin Lüpken.pdf">Product Management Portfolio PDF</a> 
  <br>
  <a href="mailto:kristinluepken@yahoo.de">Email Me</a>


  <br><br>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
