title: Kristin Lüpken # your name (or website title) here
logo: "images/Kristin2-modified(1).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Product Management | Customer Success | Data Analytics
  <br><br>
  My competency lies in understanding and driving businesses from a user perspective with a mindset for growth. 
  I’m good at bringing direction, structure and clarity to complex matters and have a track record of working with interdisciplinary teams towards common goals. 
  <br><br>
  <a href="mailto:kristinluepken@yahoo.de">Email Me</a>
  <br>
  <a href="https://www.linkedin.com/in/kristin-l%C3%BCpken-b4149984/">LinkedIn Profile</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/kristin.l.pken/vizzes">Public Tableau</a> 
  <br>
  <a href="https://github.com/klue-git">GitHub Repo</a> 
  <br>
  <a href="pdf/Data Analytics Portfolio Kristin Lüpken.pdf">Data Analytics Project Portfolio PDF</a> 
  <br>
  <a href="pdf/Product Manager Portfolio Kristin Lüpken.pdf">Product Management Portfolio PDF</a> 
  <br><br>
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
